version: "3.9"
services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./:/src
    entrypoint:
      - python
      - src/redis_consumer.py

  api:
    image: allocation-image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis_pubsub
    volumes:
      - ./:/src
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: uvicorn src.app:api --host 0.0.0.0 --port 80 --reload
    ports:
      - "5005:80"

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  redis:
    image: redis:alpine
    ports:
      - "63791:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "11025:1025"
      - "18025:8025"
